[0]
Meter=String
MeterStyle=s
Text=Default
LeftMouseDownAction=[!SetVariable AudioDeviceID "" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "" "C:\Users\Pichau\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Default" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[1]
Meter=String
MeterStyle=s
Text=Saída Digital (4- AMD High Definition Audio Device)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{2941cc26-14ae-43c1-988e-9ba38b38aad1}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{2941cc26-14ae-43c1-988e-9ba38b38aad1}" "C:\Users\Pichau\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Saída Digital (4- AMD High Definition Audio Device)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[2]
Meter=String
MeterStyle=s
Text=Saída Digital (4- AMD High Definition Audio Device)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{3ea6e89e-c16b-4fe4-80d0-a112d70f80f9}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{3ea6e89e-c16b-4fe4-80d0-a112d70f80f9}" "C:\Users\Pichau\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Saída Digital (4- AMD High Definition Audio Device)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[3]
Meter=String
MeterStyle=s
Text=Alto-falantes (Realtek(R) Audio)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{55da4a1f-adcc-4744-a06d-073112582444}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{55da4a1f-adcc-4744-a06d-073112582444}" "C:\Users\Pichau\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Alto-falantes (Realtek(R) Audio)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[4]
Meter=String
MeterStyle=s
Text=Realtek Digital Output (Realtek(R) Audio)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{90c34210-083b-4398-896a-dfdbbce2a481}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{90c34210-083b-4398-896a-dfdbbce2a481}" "C:\Users\Pichau\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Realtek Digital Output (Realtek(R) Audio)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[5]
Meter=String
MeterStyle=s
Text=Saída Digital (4- AMD High Definition Audio Device)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{aba739b2-1cb8-4a83-b8b4-646182db7ca6}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{aba739b2-1cb8-4a83-b8b4-646182db7ca6}" "C:\Users\Pichau\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Saída Digital (4- AMD High Definition Audio Device)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[6]
Meter=String
MeterStyle=s
Text=Saída Digital (4- AMD High Definition Audio Device)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{b0862089-94a9-4ec9-ba90-c037c2dc3926}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{b0862089-94a9-4ec9-ba90-c037c2dc3926}" "C:\Users\Pichau\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "Saída Digital (4- AMD High Definition Audio Device)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
[7]
Meter=String
MeterStyle=s
Text=1 - LG HD (4- AMD High Definition Audio Device)
LeftMouseDownAction=[!SetVariable AudioDeviceID "{0.0.0.00000000}.{bb62b79d-d1a8-4209-87ed-e233382d7330}" "#ROOTCONFIG#\SettingsWindow"][!WriteKeyValue Variables AudioDeviceID "{0.0.0.00000000}.{bb62b79d-d1a8-4209-87ed-e233382d7330}" "C:\Users\Pichau\Documents\Rainmeter\Skins\VisBubble\Settings.inc"][!SetOption AudioDeviceID_Select Text "1 - LG HD (4- AMD High Definition Audio Device)" "#ROOTCONFIG#\SettingsWindow"][!Refresh "#ROOTCONFIG#\SettingsWindow"][!DeactivateConfig]
