$image = /home/luis/dotfiles/Pictures/wallpapers/rosepeak.png

$background = rgba(121415ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(2f3132ff)

$inverse_primary = rgba(3a6475ff)

$inverse_surface = rgba(e2e2e4ff)

$on_background = rgba(e2e2e4ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(013545ff)

$on_primary_container = rgba(ffffffff)

$on_primary_fixed = rgba(001f2aff)

$on_primary_fixed_variant = rgba(214c5dff)

$on_secondary = rgba(243239ff)

$on_secondary_container = rgba(d6e6efff)

$on_secondary_fixed = rgba(0e1d24ff)

$on_secondary_fixed_variant = rgba(3a4950ff)

$on_surface = rgba(e2e2e4ff)

$on_surface_variant = rgba(c1c7ccff)

$on_tertiary = rgba(3d2848ff)

$on_tertiary_container = rgba(ffffffff)

$on_tertiary_fixed = rgba(271332ff)

$on_tertiary_fixed_variant = rgba(543e60ff)

$outline = rgba(8b9296ff)

$outline_variant = rgba(41484bff)

$primary = rgba(a3cde1ff)

$primary_container = rgba(4a7385ff)

$primary_fixed = rgba(bee9feff)

$primary_fixed_dim = rgba(a3cde1ff)

$scrim = rgba(000000ff)

$secondary = rgba(b9c9d2ff)

$secondary_container = rgba(3c4b53ff)

$secondary_fixed = rgba(d5e5eeff)

$secondary_fixed_dim = rgba(b9c9d2ff)

$shadow = rgba(000000ff)

$source_color = rgba(4a7385ff)

$surface = rgba(121415ff)

$surface_bright = rgba(37393bff)

$surface_container = rgba(1e2021ff)

$surface_container_high = rgba(282a2bff)

$surface_container_highest = rgba(333536ff)

$surface_container_low = rgba(1a1c1dff)

$surface_container_lowest = rgba(0c0e10ff)

$surface_dim = rgba(121415ff)

$surface_tint = rgba(a3cde1ff)

$surface_variant = rgba(41484bff)

$tertiary = rgba(d9bde5ff)

$tertiary_container = rgba(7d6589ff)

$tertiary_fixed = rgba(f5d9ffff)

$tertiary_fixed_dim = rgba(d9bde5ff)

