# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e2e2e4"

# Title color for boxes
theme[title]="#a3cde1"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b9c9d2"

# Background color of selected item in processes box
theme[selected_bg]="#a3cde1"

# Foreground color of selected item in processes box
theme[selected_fg]="#013545"

# Color of inactive/disabled text
theme[inactive_fg]="#c1c7cc"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d9bde5"

# Cpu box outline color
theme[cpu_box]="#8b9296"

# Memory/disks box outline color
theme[mem_box]="#8b9296"

# Net up/down box outline color
theme[net_box]="#8b9296"

# Processes box outline color
theme[proc_box]="#8b9296"

# Box divider line and small boxes line color
theme[div_line]="#41484b"

# Temperature graph colors
theme[temp_start]="#b9c9d2"
theme[temp_mid]="#a3cde1"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#b9c9d2"
theme[cpu_mid]="#a3cde1"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#b9c9d2"
theme[free_mid]=""
theme[free_end]="#3c4b53"

# Mem/Disk cached meter
theme[cached_start]="#d9bde5"
theme[cached_mid]=""
theme[cached_end]="#7d6589"

# Mem/Disk available meter
theme[available_start]="#a3cde1"
theme[available_mid]=""
theme[available_end]="#4a7385"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#b9c9d2"
theme[download_mid]="#a3cde1"
theme[download_end]="#d9bde5"

# Upload graph colors
theme[upload_start]="#b9c9d2"
theme[upload_mid]="#a3cde1"
theme[upload_end]="#d9bde5"