#!/usr/bin/env bash
set -euo pipefail

# Configuration
WALLDIR="$HOME/Pictures/wallpapers"
ROFI_THEME="$HOME/.config/rofi/config-wallpaper.rasi"
EXTS=(jpg jpeg png webp)

generate_wallpaper_list() {
    shopt -s nullglob
    for ext in "${EXTS[@]}"; do
        for img in "$WALLDIR"/*."$ext"; do
            name="$(basename "$img")"
            printf "%s\x00icon\x1f%s\n" "$name" "$img"
        done
    done
}

selection="$(generate_wallpaper_list | rofi \
    -dmenu \
    -i \
    -show-icons \
    -theme $ROFI_THEME
)"

[ -z "$selection" ] && exit 0

image_path="$WALLDIR/$selection"

if [ ! -f "$image_path" ]; then
    notify-send "Wallpaper selector" "File not found:\n$image_path"
    exit 1
fi

matugen image "$image_path" --type scheme-content

notify-send "Wallpaper updated" -a "Matugen" -u "low" -i "$image_path"
